'pensieve-database':
  image: postgres:9.3.10
  environment:
    POSTGRES_USER: pensieve
    POSTGRES_PASSWORD: pensieve
    POSTGRES_DB: memories
    PGDATA: /var/pensieve/data
  ports:
    - "5555:5432"
  volumes:
    - /postgres/pensieve:/var/pensieve/data

'pensieve-app':
  image: rajivrnair/pensieve
  ports:
    - "80:8080"
  links:
    - 'pensieve-database'
